version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
